apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflixweb
spec:
  replicas: 4
  minReadySeconds: 45
  strategy:
    type: RollingUpdate  
    rollingUpdate: 
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: netflixapp
  template:
    metadata: 
      name: netflixapp-pod
      labels:
        app: netflixapp
    spec: 
      containers:
        - name: netflixapp
          image: vishwaranjanpandey/netflix
          imagePullPolicy : Always
          resources:
            limits: 
              memory: 1000Mi 
              cpu: 500m
            requests:
              memory: 500Mi
              cpu: 250m 
---
apiVersion: v1
kind: Service 
metadata: 
  name: netflix-svc
spec:
  selector:
    app: netflixapp
  type: LoadBalancer
  ports:
    - port: 1234       
      nodePort: 32103
      targetPort: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: netflix-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: netflixweb
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization  
          averageUtilization: 60


