apiVersion: v1
kind: PersistentVolume
metadata:
  name: netflix-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1000Mi
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: /tmp/netflixdatapv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: netflix-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 700Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflixweb
spec:
  replicas: 4
  minReadySeconds: 45
  strategy:
    type: RollingUpdate  
    rollingUpdate: 
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: netflixapp
  template:
    metadata: 
      name: netflixapp-pod
      labels:
        app: netflixapp
    spec: 
      containers:
        - name: netflixapp
          image: vishwaranjanpandey/netflix
          imagePullPolicy: Always
          resources:
            limits:
              memory: 1000Mi
              cpu: 500m
            requests:
              memory: 500Mi
              cpu: 250m
          volumeMounts:    
            - name: netflix-pv
              mountPath: /var/log/nginx/
      volumes:
        - name: netflix-pv
          persistentVolumeClaim:
            claimName: netflix-pvc


---
apiVersion: v1
kind: Service 
metadata: 
  name: netflix-svc
spec:
  selector:
    app: netflixapp
  type: LoadBalancer
  ports:
    - port: 1234       
      nodePort: 32103
      targetPort: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: netflix-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: netflixweb
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization  
          averageUtilization: 40


